spring.application.name=airBnbApp

## DB Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

## Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

## Faster startup
spring.main.lazy-initialization=true
spring.main.banner-mode=off

#Caching Configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=${REDIS_SSL}

## HikariCP (good for small Render instances)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

## Server
server.port=${PORT:8080}
server.servlet.context-path=/api/v1

## JWT
jwt.jwtSecretKey=${JWT_SECRET}

## Frontend
frontend.url=${FRONTEND_URL}

## Stripe
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}