/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MgrRouteImport } from './routes/_mgr'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelsHotelIdRouteImport } from './routes/hotels.$hotelId'
import { Route as MgrManagerRouteImport } from './routes/_mgr.manager'
import { Route as AuthAccountRouteImport } from './routes/_auth.account'
import { Route as MgrManagerIndexRouteImport } from './routes/_mgr.manager.index'
import { Route as AuthAccountIndexRouteImport } from './routes/_auth.account.index'
import { Route as PaymentsBookingIdStatusRouteImport } from './routes/payments.$bookingId.status'
import { Route as MgrManagerHotelsRouteImport } from './routes/_mgr.manager.hotels'
import { Route as AuthAccountProfileRouteImport } from './routes/_auth.account.profile'
import { Route as AuthAccountGuestsRouteImport } from './routes/_auth.account.guests'
import { Route as AuthAccountBookingsRouteImport } from './routes/_auth.account.bookings'
import { Route as MgrManagerHotelsNewRouteImport } from './routes/_mgr.manager.hotels.new'
import { Route as MgrManagerHotelsHotelIdRouteImport } from './routes/_mgr.manager.hotels.$hotelId'
import { Route as AuthBookingHotelIdRoomIdRouteImport } from './routes/_auth.booking.$hotelId.$roomId'
import { Route as MgrManagerHotelsHotelIdRoomsRouteImport } from './routes/_mgr.manager.hotels.$hotelId.rooms'
import { Route as MgrManagerHotelsHotelIdReportsRouteImport } from './routes/_mgr.manager.hotels.$hotelId.reports'
import { Route as MgrManagerHotelsHotelIdEditRouteImport } from './routes/_mgr.manager.hotels.$hotelId.edit'
import { Route as MgrManagerHotelsHotelIdBookingsRouteImport } from './routes/_mgr.manager.hotels.$hotelId.bookings'
import { Route as MgrManagerHotelsHotelIdRoomsRoomIdInventoryRouteImport } from './routes/_mgr.manager.hotels.$hotelId.rooms.$roomId.inventory'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MgrRoute = MgrRouteImport.update({
  id: '/_mgr',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsHotelIdRoute = HotelsHotelIdRouteImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)
const MgrManagerRoute = MgrManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => MgrRoute,
} as any)
const AuthAccountRoute = AuthAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthRoute,
} as any)
const MgrManagerIndexRoute = MgrManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MgrManagerRoute,
} as any)
const AuthAccountIndexRoute = AuthAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAccountRoute,
} as any)
const PaymentsBookingIdStatusRoute = PaymentsBookingIdStatusRouteImport.update({
  id: '/payments/$bookingId/status',
  path: '/payments/$bookingId/status',
  getParentRoute: () => rootRouteImport,
} as any)
const MgrManagerHotelsRoute = MgrManagerHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => MgrManagerRoute,
} as any)
const AuthAccountProfileRoute = AuthAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthAccountRoute,
} as any)
const AuthAccountGuestsRoute = AuthAccountGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AuthAccountRoute,
} as any)
const AuthAccountBookingsRoute = AuthAccountBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthAccountRoute,
} as any)
const MgrManagerHotelsNewRoute = MgrManagerHotelsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MgrManagerHotelsRoute,
} as any)
const MgrManagerHotelsHotelIdRoute = MgrManagerHotelsHotelIdRouteImport.update({
  id: '/$hotelId',
  path: '/$hotelId',
  getParentRoute: () => MgrManagerHotelsRoute,
} as any)
const AuthBookingHotelIdRoomIdRoute =
  AuthBookingHotelIdRoomIdRouteImport.update({
    id: '/booking/$hotelId/$roomId',
    path: '/booking/$hotelId/$roomId',
    getParentRoute: () => AuthRoute,
  } as any)
const MgrManagerHotelsHotelIdRoomsRoute =
  MgrManagerHotelsHotelIdRoomsRouteImport.update({
    id: '/rooms',
    path: '/rooms',
    getParentRoute: () => MgrManagerHotelsHotelIdRoute,
  } as any)
const MgrManagerHotelsHotelIdReportsRoute =
  MgrManagerHotelsHotelIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => MgrManagerHotelsHotelIdRoute,
  } as any)
const MgrManagerHotelsHotelIdEditRoute =
  MgrManagerHotelsHotelIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => MgrManagerHotelsHotelIdRoute,
  } as any)
const MgrManagerHotelsHotelIdBookingsRoute =
  MgrManagerHotelsHotelIdBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => MgrManagerHotelsHotelIdRoute,
  } as any)
const MgrManagerHotelsHotelIdRoomsRoomIdInventoryRoute =
  MgrManagerHotelsHotelIdRoomsRoomIdInventoryRouteImport.update({
    id: '/$roomId/inventory',
    path: '/$roomId/inventory',
    getParentRoute: () => MgrManagerHotelsHotelIdRoomsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthAccountRouteWithChildren
  '/manager': typeof MgrManagerRouteWithChildren
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/account/bookings': typeof AuthAccountBookingsRoute
  '/account/guests': typeof AuthAccountGuestsRoute
  '/account/profile': typeof AuthAccountProfileRoute
  '/manager/hotels': typeof MgrManagerHotelsRouteWithChildren
  '/payments/$bookingId/status': typeof PaymentsBookingIdStatusRoute
  '/account/': typeof AuthAccountIndexRoute
  '/manager/': typeof MgrManagerIndexRoute
  '/booking/$hotelId/$roomId': typeof AuthBookingHotelIdRoomIdRoute
  '/manager/hotels/$hotelId': typeof MgrManagerHotelsHotelIdRouteWithChildren
  '/manager/hotels/new': typeof MgrManagerHotelsNewRoute
  '/manager/hotels/$hotelId/bookings': typeof MgrManagerHotelsHotelIdBookingsRoute
  '/manager/hotels/$hotelId/edit': typeof MgrManagerHotelsHotelIdEditRoute
  '/manager/hotels/$hotelId/reports': typeof MgrManagerHotelsHotelIdReportsRoute
  '/manager/hotels/$hotelId/rooms': typeof MgrManagerHotelsHotelIdRoomsRouteWithChildren
  '/manager/hotels/$hotelId/rooms/$roomId/inventory': typeof MgrManagerHotelsHotelIdRoomsRoomIdInventoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/account/bookings': typeof AuthAccountBookingsRoute
  '/account/guests': typeof AuthAccountGuestsRoute
  '/account/profile': typeof AuthAccountProfileRoute
  '/manager/hotels': typeof MgrManagerHotelsRouteWithChildren
  '/payments/$bookingId/status': typeof PaymentsBookingIdStatusRoute
  '/account': typeof AuthAccountIndexRoute
  '/manager': typeof MgrManagerIndexRoute
  '/booking/$hotelId/$roomId': typeof AuthBookingHotelIdRoomIdRoute
  '/manager/hotels/$hotelId': typeof MgrManagerHotelsHotelIdRouteWithChildren
  '/manager/hotels/new': typeof MgrManagerHotelsNewRoute
  '/manager/hotels/$hotelId/bookings': typeof MgrManagerHotelsHotelIdBookingsRoute
  '/manager/hotels/$hotelId/edit': typeof MgrManagerHotelsHotelIdEditRoute
  '/manager/hotels/$hotelId/reports': typeof MgrManagerHotelsHotelIdReportsRoute
  '/manager/hotels/$hotelId/rooms': typeof MgrManagerHotelsHotelIdRoomsRouteWithChildren
  '/manager/hotels/$hotelId/rooms/$roomId/inventory': typeof MgrManagerHotelsHotelIdRoomsRoomIdInventoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_mgr': typeof MgrRouteWithChildren
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/_auth/account': typeof AuthAccountRouteWithChildren
  '/_mgr/manager': typeof MgrManagerRouteWithChildren
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/_auth/account/bookings': typeof AuthAccountBookingsRoute
  '/_auth/account/guests': typeof AuthAccountGuestsRoute
  '/_auth/account/profile': typeof AuthAccountProfileRoute
  '/_mgr/manager/hotels': typeof MgrManagerHotelsRouteWithChildren
  '/payments/$bookingId/status': typeof PaymentsBookingIdStatusRoute
  '/_auth/account/': typeof AuthAccountIndexRoute
  '/_mgr/manager/': typeof MgrManagerIndexRoute
  '/_auth/booking/$hotelId/$roomId': typeof AuthBookingHotelIdRoomIdRoute
  '/_mgr/manager/hotels/$hotelId': typeof MgrManagerHotelsHotelIdRouteWithChildren
  '/_mgr/manager/hotels/new': typeof MgrManagerHotelsNewRoute
  '/_mgr/manager/hotels/$hotelId/bookings': typeof MgrManagerHotelsHotelIdBookingsRoute
  '/_mgr/manager/hotels/$hotelId/edit': typeof MgrManagerHotelsHotelIdEditRoute
  '/_mgr/manager/hotels/$hotelId/reports': typeof MgrManagerHotelsHotelIdReportsRoute
  '/_mgr/manager/hotels/$hotelId/rooms': typeof MgrManagerHotelsHotelIdRoomsRouteWithChildren
  '/_mgr/manager/hotels/$hotelId/rooms/$roomId/inventory': typeof MgrManagerHotelsHotelIdRoomsRoomIdInventoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/search'
    | '/signup'
    | '/account'
    | '/manager'
    | '/hotels/$hotelId'
    | '/account/bookings'
    | '/account/guests'
    | '/account/profile'
    | '/manager/hotels'
    | '/payments/$bookingId/status'
    | '/account/'
    | '/manager/'
    | '/booking/$hotelId/$roomId'
    | '/manager/hotels/$hotelId'
    | '/manager/hotels/new'
    | '/manager/hotels/$hotelId/bookings'
    | '/manager/hotels/$hotelId/edit'
    | '/manager/hotels/$hotelId/reports'
    | '/manager/hotels/$hotelId/rooms'
    | '/manager/hotels/$hotelId/rooms/$roomId/inventory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/search'
    | '/signup'
    | '/hotels/$hotelId'
    | '/account/bookings'
    | '/account/guests'
    | '/account/profile'
    | '/manager/hotels'
    | '/payments/$bookingId/status'
    | '/account'
    | '/manager'
    | '/booking/$hotelId/$roomId'
    | '/manager/hotels/$hotelId'
    | '/manager/hotels/new'
    | '/manager/hotels/$hotelId/bookings'
    | '/manager/hotels/$hotelId/edit'
    | '/manager/hotels/$hotelId/reports'
    | '/manager/hotels/$hotelId/rooms'
    | '/manager/hotels/$hotelId/rooms/$roomId/inventory'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_mgr'
    | '/login'
    | '/search'
    | '/signup'
    | '/_auth/account'
    | '/_mgr/manager'
    | '/hotels/$hotelId'
    | '/_auth/account/bookings'
    | '/_auth/account/guests'
    | '/_auth/account/profile'
    | '/_mgr/manager/hotels'
    | '/payments/$bookingId/status'
    | '/_auth/account/'
    | '/_mgr/manager/'
    | '/_auth/booking/$hotelId/$roomId'
    | '/_mgr/manager/hotels/$hotelId'
    | '/_mgr/manager/hotels/new'
    | '/_mgr/manager/hotels/$hotelId/bookings'
    | '/_mgr/manager/hotels/$hotelId/edit'
    | '/_mgr/manager/hotels/$hotelId/reports'
    | '/_mgr/manager/hotels/$hotelId/rooms'
    | '/_mgr/manager/hotels/$hotelId/rooms/$roomId/inventory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  MgrRoute: typeof MgrRouteWithChildren
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  HotelsHotelIdRoute: typeof HotelsHotelIdRoute
  PaymentsBookingIdStatusRoute: typeof PaymentsBookingIdStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mgr': {
      id: '/_mgr'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MgrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId': {
      id: '/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof HotelsHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mgr/manager': {
      id: '/_mgr/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof MgrManagerRouteImport
      parentRoute: typeof MgrRoute
    }
    '/_auth/account': {
      id: '/_auth/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthAccountRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_mgr/manager/': {
      id: '/_mgr/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof MgrManagerIndexRouteImport
      parentRoute: typeof MgrManagerRoute
    }
    '/_auth/account/': {
      id: '/_auth/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthAccountIndexRouteImport
      parentRoute: typeof AuthAccountRoute
    }
    '/payments/$bookingId/status': {
      id: '/payments/$bookingId/status'
      path: '/payments/$bookingId/status'
      fullPath: '/payments/$bookingId/status'
      preLoaderRoute: typeof PaymentsBookingIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mgr/manager/hotels': {
      id: '/_mgr/manager/hotels'
      path: '/hotels'
      fullPath: '/manager/hotels'
      preLoaderRoute: typeof MgrManagerHotelsRouteImport
      parentRoute: typeof MgrManagerRoute
    }
    '/_auth/account/profile': {
      id: '/_auth/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthAccountProfileRouteImport
      parentRoute: typeof AuthAccountRoute
    }
    '/_auth/account/guests': {
      id: '/_auth/account/guests'
      path: '/guests'
      fullPath: '/account/guests'
      preLoaderRoute: typeof AuthAccountGuestsRouteImport
      parentRoute: typeof AuthAccountRoute
    }
    '/_auth/account/bookings': {
      id: '/_auth/account/bookings'
      path: '/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AuthAccountBookingsRouteImport
      parentRoute: typeof AuthAccountRoute
    }
    '/_mgr/manager/hotels/new': {
      id: '/_mgr/manager/hotels/new'
      path: '/new'
      fullPath: '/manager/hotels/new'
      preLoaderRoute: typeof MgrManagerHotelsNewRouteImport
      parentRoute: typeof MgrManagerHotelsRoute
    }
    '/_mgr/manager/hotels/$hotelId': {
      id: '/_mgr/manager/hotels/$hotelId'
      path: '/$hotelId'
      fullPath: '/manager/hotels/$hotelId'
      preLoaderRoute: typeof MgrManagerHotelsHotelIdRouteImport
      parentRoute: typeof MgrManagerHotelsRoute
    }
    '/_auth/booking/$hotelId/$roomId': {
      id: '/_auth/booking/$hotelId/$roomId'
      path: '/booking/$hotelId/$roomId'
      fullPath: '/booking/$hotelId/$roomId'
      preLoaderRoute: typeof AuthBookingHotelIdRoomIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_mgr/manager/hotels/$hotelId/rooms': {
      id: '/_mgr/manager/hotels/$hotelId/rooms'
      path: '/rooms'
      fullPath: '/manager/hotels/$hotelId/rooms'
      preLoaderRoute: typeof MgrManagerHotelsHotelIdRoomsRouteImport
      parentRoute: typeof MgrManagerHotelsHotelIdRoute
    }
    '/_mgr/manager/hotels/$hotelId/reports': {
      id: '/_mgr/manager/hotels/$hotelId/reports'
      path: '/reports'
      fullPath: '/manager/hotels/$hotelId/reports'
      preLoaderRoute: typeof MgrManagerHotelsHotelIdReportsRouteImport
      parentRoute: typeof MgrManagerHotelsHotelIdRoute
    }
    '/_mgr/manager/hotels/$hotelId/edit': {
      id: '/_mgr/manager/hotels/$hotelId/edit'
      path: '/edit'
      fullPath: '/manager/hotels/$hotelId/edit'
      preLoaderRoute: typeof MgrManagerHotelsHotelIdEditRouteImport
      parentRoute: typeof MgrManagerHotelsHotelIdRoute
    }
    '/_mgr/manager/hotels/$hotelId/bookings': {
      id: '/_mgr/manager/hotels/$hotelId/bookings'
      path: '/bookings'
      fullPath: '/manager/hotels/$hotelId/bookings'
      preLoaderRoute: typeof MgrManagerHotelsHotelIdBookingsRouteImport
      parentRoute: typeof MgrManagerHotelsHotelIdRoute
    }
    '/_mgr/manager/hotels/$hotelId/rooms/$roomId/inventory': {
      id: '/_mgr/manager/hotels/$hotelId/rooms/$roomId/inventory'
      path: '/$roomId/inventory'
      fullPath: '/manager/hotels/$hotelId/rooms/$roomId/inventory'
      preLoaderRoute: typeof MgrManagerHotelsHotelIdRoomsRoomIdInventoryRouteImport
      parentRoute: typeof MgrManagerHotelsHotelIdRoomsRoute
    }
  }
}

interface AuthAccountRouteChildren {
  AuthAccountBookingsRoute: typeof AuthAccountBookingsRoute
  AuthAccountGuestsRoute: typeof AuthAccountGuestsRoute
  AuthAccountProfileRoute: typeof AuthAccountProfileRoute
  AuthAccountIndexRoute: typeof AuthAccountIndexRoute
}

const AuthAccountRouteChildren: AuthAccountRouteChildren = {
  AuthAccountBookingsRoute: AuthAccountBookingsRoute,
  AuthAccountGuestsRoute: AuthAccountGuestsRoute,
  AuthAccountProfileRoute: AuthAccountProfileRoute,
  AuthAccountIndexRoute: AuthAccountIndexRoute,
}

const AuthAccountRouteWithChildren = AuthAccountRoute._addFileChildren(
  AuthAccountRouteChildren,
)

interface AuthRouteChildren {
  AuthAccountRoute: typeof AuthAccountRouteWithChildren
  AuthBookingHotelIdRoomIdRoute: typeof AuthBookingHotelIdRoomIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountRoute: AuthAccountRouteWithChildren,
  AuthBookingHotelIdRoomIdRoute: AuthBookingHotelIdRoomIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MgrManagerHotelsHotelIdRoomsRouteChildren {
  MgrManagerHotelsHotelIdRoomsRoomIdInventoryRoute: typeof MgrManagerHotelsHotelIdRoomsRoomIdInventoryRoute
}

const MgrManagerHotelsHotelIdRoomsRouteChildren: MgrManagerHotelsHotelIdRoomsRouteChildren =
  {
    MgrManagerHotelsHotelIdRoomsRoomIdInventoryRoute:
      MgrManagerHotelsHotelIdRoomsRoomIdInventoryRoute,
  }

const MgrManagerHotelsHotelIdRoomsRouteWithChildren =
  MgrManagerHotelsHotelIdRoomsRoute._addFileChildren(
    MgrManagerHotelsHotelIdRoomsRouteChildren,
  )

interface MgrManagerHotelsHotelIdRouteChildren {
  MgrManagerHotelsHotelIdBookingsRoute: typeof MgrManagerHotelsHotelIdBookingsRoute
  MgrManagerHotelsHotelIdEditRoute: typeof MgrManagerHotelsHotelIdEditRoute
  MgrManagerHotelsHotelIdReportsRoute: typeof MgrManagerHotelsHotelIdReportsRoute
  MgrManagerHotelsHotelIdRoomsRoute: typeof MgrManagerHotelsHotelIdRoomsRouteWithChildren
}

const MgrManagerHotelsHotelIdRouteChildren: MgrManagerHotelsHotelIdRouteChildren =
  {
    MgrManagerHotelsHotelIdBookingsRoute: MgrManagerHotelsHotelIdBookingsRoute,
    MgrManagerHotelsHotelIdEditRoute: MgrManagerHotelsHotelIdEditRoute,
    MgrManagerHotelsHotelIdReportsRoute: MgrManagerHotelsHotelIdReportsRoute,
    MgrManagerHotelsHotelIdRoomsRoute:
      MgrManagerHotelsHotelIdRoomsRouteWithChildren,
  }

const MgrManagerHotelsHotelIdRouteWithChildren =
  MgrManagerHotelsHotelIdRoute._addFileChildren(
    MgrManagerHotelsHotelIdRouteChildren,
  )

interface MgrManagerHotelsRouteChildren {
  MgrManagerHotelsHotelIdRoute: typeof MgrManagerHotelsHotelIdRouteWithChildren
  MgrManagerHotelsNewRoute: typeof MgrManagerHotelsNewRoute
}

const MgrManagerHotelsRouteChildren: MgrManagerHotelsRouteChildren = {
  MgrManagerHotelsHotelIdRoute: MgrManagerHotelsHotelIdRouteWithChildren,
  MgrManagerHotelsNewRoute: MgrManagerHotelsNewRoute,
}

const MgrManagerHotelsRouteWithChildren =
  MgrManagerHotelsRoute._addFileChildren(MgrManagerHotelsRouteChildren)

interface MgrManagerRouteChildren {
  MgrManagerHotelsRoute: typeof MgrManagerHotelsRouteWithChildren
  MgrManagerIndexRoute: typeof MgrManagerIndexRoute
}

const MgrManagerRouteChildren: MgrManagerRouteChildren = {
  MgrManagerHotelsRoute: MgrManagerHotelsRouteWithChildren,
  MgrManagerIndexRoute: MgrManagerIndexRoute,
}

const MgrManagerRouteWithChildren = MgrManagerRoute._addFileChildren(
  MgrManagerRouteChildren,
)

interface MgrRouteChildren {
  MgrManagerRoute: typeof MgrManagerRouteWithChildren
}

const MgrRouteChildren: MgrRouteChildren = {
  MgrManagerRoute: MgrManagerRouteWithChildren,
}

const MgrRouteWithChildren = MgrRoute._addFileChildren(MgrRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  MgrRoute: MgrRouteWithChildren,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  HotelsHotelIdRoute: HotelsHotelIdRoute,
  PaymentsBookingIdStatusRoute: PaymentsBookingIdStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
